// <auto-generated />
using CqrsDemoWebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CqrsDemoWebApi.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20220707213619_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CqrsDemoWebApi.Database.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Chinua Achebe",
                            Country = "Nigeria",
                            ImageLink = "images/things-fall-apart.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
                            Pages = 209,
                            Title = "Things Fall Apart",
                            Year = 1958
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Hans Christian Andersen",
                            Country = "Denmark",
                            ImageLink = "images/fairy-tales.jpg",
                            Language = "Danish",
                            Link = "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
                            Pages = 784,
                            Title = "Fairy tales",
                            Year = 1836
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Dante Alighieri",
                            Country = "Italy",
                            ImageLink = "images/the-divine-comedy.jpg",
                            Language = "Italian",
                            Link = "https://en.wikipedia.org/wiki/Divine_Comedy\n",
                            Pages = 928,
                            Title = "The Divine Comedy",
                            Year = 1315
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Unknown",
                            Country = "Sumer and Akkadian Empire",
                            ImageLink = "images/the-epic-of-gilgamesh.jpg",
                            Language = "Akkadian",
                            Link = "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
                            Pages = 160,
                            Title = "The Epic Of Gilgamesh",
                            Year = -1700
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Unknown",
                            Country = "Achaemenid Empire",
                            ImageLink = "images/the-book-of-job.jpg",
                            Language = "Hebrew",
                            Link = "https://en.wikipedia.org/wiki/Book_of_Job\n",
                            Pages = 176,
                            Title = "The Book Of Job",
                            Year = -600
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Unknown",
                            Country = "India/Iran/Iraq/Egypt/Tajikistan",
                            ImageLink = "images/one-thousand-and-one-nights.jpg",
                            Language = "Arabic",
                            Link = "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
                            Pages = 288,
                            Title = "One Thousand and One Nights",
                            Year = 1200
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Unknown",
                            Country = "Iceland",
                            ImageLink = "images/njals-saga.jpg",
                            Language = "Old Norse",
                            Link = "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
                            Pages = 384,
                            Title = "Njál's Saga",
                            Year = 1350
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Jane Austen",
                            Country = "United Kingdom",
                            ImageLink = "images/pride-and-prejudice.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
                            Pages = 226,
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Honoré de Balzac",
                            Country = "France",
                            ImageLink = "images/le-pere-goriot.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
                            Pages = 443,
                            Title = "Le Père Goriot",
                            Year = 1835
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Samuel Beckett",
                            Country = "Republic of Ireland",
                            ImageLink = "images/molloy-malone-dies-the-unnamable.jpg",
                            Language = "French, English",
                            Link = "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
                            Pages = 256,
                            Title = "Molloy, Malone Dies, The Unnamable, the trilogy",
                            Year = 1952
                        },
                        new
                        {
                            BookId = 11,
                            Author = "Giovanni Boccaccio",
                            Country = "Italy",
                            ImageLink = "images/the-decameron.jpg",
                            Language = "Italian",
                            Link = "https://en.wikipedia.org/wiki/The_Decameron\n",
                            Pages = 1024,
                            Title = "The Decameron",
                            Year = 1351
                        },
                        new
                        {
                            BookId = 12,
                            Author = "Jorge Luis Borges",
                            Country = "Argentina",
                            ImageLink = "images/ficciones.jpg",
                            Language = "Spanish",
                            Link = "https://en.wikipedia.org/wiki/Ficciones\n",
                            Pages = 224,
                            Title = "Ficciones",
                            Year = 1965
                        },
                        new
                        {
                            BookId = 13,
                            Author = "Emily Brontë",
                            Country = "United Kingdom",
                            ImageLink = "images/wuthering-heights.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
                            Pages = 342,
                            Title = "Wuthering Heights",
                            Year = 1847
                        },
                        new
                        {
                            BookId = 14,
                            Author = "Albert Camus",
                            Country = "Algeria, French Empire",
                            ImageLink = "images/l-etranger.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
                            Pages = 185,
                            Title = "The Stranger",
                            Year = 1942
                        },
                        new
                        {
                            BookId = 15,
                            Author = "Paul Celan",
                            Country = "Romania, France",
                            ImageLink = "images/poems-paul-celan.jpg",
                            Language = "German",
                            Link = "\n",
                            Pages = 320,
                            Title = "Poems",
                            Year = 1952
                        },
                        new
                        {
                            BookId = 16,
                            Author = "Louis-Ferdinand Céline",
                            Country = "France",
                            ImageLink = "images/voyage-au-bout-de-la-nuit.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
                            Pages = 505,
                            Title = "Journey to the End of the Night",
                            Year = 1932
                        },
                        new
                        {
                            BookId = 17,
                            Author = "Miguel de Cervantes",
                            Country = "Spain",
                            ImageLink = "images/don-quijote-de-la-mancha.jpg",
                            Language = "Spanish",
                            Link = "https://en.wikipedia.org/wiki/Don_Quixote\n",
                            Pages = 1056,
                            Title = "Don Quijote De La Mancha",
                            Year = 1610
                        },
                        new
                        {
                            BookId = 18,
                            Author = "Geoffrey Chaucer",
                            Country = "England",
                            ImageLink = "images/the-canterbury-tales.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
                            Pages = 544,
                            Title = "The Canterbury Tales",
                            Year = 1450
                        },
                        new
                        {
                            BookId = 19,
                            Author = "Anton Chekhov",
                            Country = "Russia",
                            ImageLink = "images/stories-of-anton-chekhov.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
                            Pages = 194,
                            Title = "Stories",
                            Year = 1886
                        },
                        new
                        {
                            BookId = 20,
                            Author = "Joseph Conrad",
                            Country = "United Kingdom",
                            ImageLink = "images/nostromo.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Nostromo\n",
                            Pages = 320,
                            Title = "Nostromo",
                            Year = 1904
                        },
                        new
                        {
                            BookId = 21,
                            Author = "Charles Dickens",
                            Country = "United Kingdom",
                            ImageLink = "images/great-expectations.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Great_Expectations\n",
                            Pages = 194,
                            Title = "Great Expectations",
                            Year = 1861
                        },
                        new
                        {
                            BookId = 22,
                            Author = "Denis Diderot",
                            Country = "France",
                            ImageLink = "images/jacques-the-fatalist.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
                            Pages = 596,
                            Title = "Jacques the Fatalist",
                            Year = 1796
                        },
                        new
                        {
                            BookId = 23,
                            Author = "Alfred Döblin",
                            Country = "Germany",
                            ImageLink = "images/berlin-alexanderplatz.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
                            Pages = 600,
                            Title = "Berlin Alexanderplatz",
                            Year = 1929
                        },
                        new
                        {
                            BookId = 24,
                            Author = "Fyodor Dostoevsky",
                            Country = "Russia",
                            ImageLink = "images/crime-and-punishment.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
                            Pages = 551,
                            Title = "Crime and Punishment",
                            Year = 1866
                        },
                        new
                        {
                            BookId = 25,
                            Author = "Fyodor Dostoevsky",
                            Country = "Russia",
                            ImageLink = "images/the-idiot.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/The_Idiot\n",
                            Pages = 656,
                            Title = "The Idiot",
                            Year = 1869
                        },
                        new
                        {
                            BookId = 26,
                            Author = "Fyodor Dostoevsky",
                            Country = "Russia",
                            ImageLink = "images/the-possessed.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
                            Pages = 768,
                            Title = "The Possessed",
                            Year = 1872
                        },
                        new
                        {
                            BookId = 27,
                            Author = "Fyodor Dostoevsky",
                            Country = "Russia",
                            ImageLink = "images/the-brothers-karamazov.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
                            Pages = 824,
                            Title = "The Brothers Karamazov",
                            Year = 1880
                        },
                        new
                        {
                            BookId = 28,
                            Author = "George Eliot",
                            Country = "United Kingdom",
                            ImageLink = "images/middlemarch.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Middlemarch\n",
                            Pages = 800,
                            Title = "Middlemarch",
                            Year = 1871
                        },
                        new
                        {
                            BookId = 29,
                            Author = "Ralph Ellison",
                            Country = "United States",
                            ImageLink = "images/invisible-man.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Invisible_Man\n",
                            Pages = 581,
                            Title = "Invisible Man",
                            Year = 1952
                        },
                        new
                        {
                            BookId = 30,
                            Author = "Euripides",
                            Country = "Greece",
                            ImageLink = "images/medea.jpg",
                            Language = "Greek",
                            Link = "https://en.wikipedia.org/wiki/Medea_(play)\n",
                            Pages = 104,
                            Title = "Medea",
                            Year = -431
                        },
                        new
                        {
                            BookId = 31,
                            Author = "William Faulkner",
                            Country = "United States",
                            ImageLink = "images/absalom-absalom.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
                            Pages = 313,
                            Title = "Absalom, Absalom!",
                            Year = 1936
                        },
                        new
                        {
                            BookId = 32,
                            Author = "William Faulkner",
                            Country = "United States",
                            ImageLink = "images/the-sound-and-the-fury.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
                            Pages = 326,
                            Title = "The Sound and the Fury",
                            Year = 1929
                        },
                        new
                        {
                            BookId = 33,
                            Author = "Gustave Flaubert",
                            Country = "France",
                            ImageLink = "images/madame-bovary.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/Madame_Bovary\n",
                            Pages = 528,
                            Title = "Madame Bovary",
                            Year = 1857
                        },
                        new
                        {
                            BookId = 34,
                            Author = "Gustave Flaubert",
                            Country = "France",
                            ImageLink = "images/l-education-sentimentale.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/Sentimental_Education\n",
                            Pages = 606,
                            Title = "Sentimental Education",
                            Year = 1869
                        },
                        new
                        {
                            BookId = 35,
                            Author = "Federico García Lorca",
                            Country = "Spain",
                            ImageLink = "images/gypsy-ballads.jpg",
                            Language = "Spanish",
                            Link = "https://en.wikipedia.org/wiki/Gypsy_Ballads\n",
                            Pages = 218,
                            Title = "Gypsy Ballads",
                            Year = 1928
                        },
                        new
                        {
                            BookId = 36,
                            Author = "Gabriel García Márquez",
                            Country = "Colombia",
                            ImageLink = "images/one-hundred-years-of-solitude.jpg",
                            Language = "Spanish",
                            Link = "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
                            Pages = 417,
                            Title = "One Hundred Years of Solitude",
                            Year = 1967
                        },
                        new
                        {
                            BookId = 37,
                            Author = "Gabriel García Márquez",
                            Country = "Colombia",
                            ImageLink = "images/love-in-the-time-of-cholera.jpg",
                            Language = "Spanish",
                            Link = "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
                            Pages = 368,
                            Title = "Love in the Time of Cholera",
                            Year = 1985
                        },
                        new
                        {
                            BookId = 38,
                            Author = "Johann Wolfgang von Goethe",
                            Country = "Saxe-Weimar",
                            ImageLink = "images/faust.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
                            Pages = 158,
                            Title = "Faust",
                            Year = 1832
                        },
                        new
                        {
                            BookId = 39,
                            Author = "Nikolai Gogol",
                            Country = "Russia",
                            ImageLink = "images/dead-souls.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/Dead_Souls\n",
                            Pages = 432,
                            Title = "Dead Souls",
                            Year = 1842
                        },
                        new
                        {
                            BookId = 40,
                            Author = "Günter Grass",
                            Country = "Germany",
                            ImageLink = "images/the-tin-drum.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
                            Pages = 600,
                            Title = "The Tin Drum",
                            Year = 1959
                        },
                        new
                        {
                            BookId = 41,
                            Author = "João Guimarães Rosa",
                            Country = "Brazil",
                            ImageLink = "images/the-devil-to-pay-in-the-backlands.jpg",
                            Language = "Portuguese",
                            Link = "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
                            Pages = 494,
                            Title = "The Devil to Pay in the Backlands",
                            Year = 1956
                        },
                        new
                        {
                            BookId = 42,
                            Author = "Knut Hamsun",
                            Country = "Norway",
                            ImageLink = "images/hunger.jpg",
                            Language = "Norwegian",
                            Link = "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
                            Pages = 176,
                            Title = "Hunger",
                            Year = 1890
                        },
                        new
                        {
                            BookId = 43,
                            Author = "Ernest Hemingway",
                            Country = "United States",
                            ImageLink = "images/the-old-man-and-the-sea.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
                            Pages = 128,
                            Title = "The Old Man and the Sea",
                            Year = 1952
                        },
                        new
                        {
                            BookId = 44,
                            Author = "Homer",
                            Country = "Greece",
                            ImageLink = "images/the-iliad-of-homer.jpg",
                            Language = "Greek",
                            Link = "https://en.wikipedia.org/wiki/Iliad\n",
                            Pages = 608,
                            Title = "Iliad",
                            Year = -735
                        },
                        new
                        {
                            BookId = 45,
                            Author = "Homer",
                            Country = "Greece",
                            ImageLink = "images/the-odyssey-of-homer.jpg",
                            Language = "Greek",
                            Link = "https://en.wikipedia.org/wiki/Odyssey\n",
                            Pages = 374,
                            Title = "Odyssey",
                            Year = -800
                        },
                        new
                        {
                            BookId = 46,
                            Author = "Henrik Ibsen",
                            Country = "Norway",
                            ImageLink = "images/a-Dolls-house.jpg",
                            Language = "Norwegian",
                            Link = "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
                            Pages = 68,
                            Title = "A Doll's House",
                            Year = 1879
                        },
                        new
                        {
                            BookId = 47,
                            Author = "James Joyce",
                            Country = "Irish Free State",
                            ImageLink = "images/ulysses.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
                            Pages = 228,
                            Title = "Ulysses",
                            Year = 1922
                        },
                        new
                        {
                            BookId = 48,
                            Author = "Franz Kafka",
                            Country = "Czechoslovakia",
                            ImageLink = "images/stories-of-franz-kafka.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
                            Pages = 488,
                            Title = "Stories",
                            Year = 1924
                        },
                        new
                        {
                            BookId = 49,
                            Author = "Franz Kafka",
                            Country = "Czechoslovakia",
                            ImageLink = "images/the-trial.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/The_Trial\n",
                            Pages = 160,
                            Title = "The Trial",
                            Year = 1925
                        },
                        new
                        {
                            BookId = 50,
                            Author = "Franz Kafka",
                            Country = "Czechoslovakia",
                            ImageLink = "images/the-castle.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
                            Pages = 352,
                            Title = "The Castle",
                            Year = 1926
                        },
                        new
                        {
                            BookId = 51,
                            Author = "Kālidāsa",
                            Country = "India",
                            ImageLink = "images/the-recognition-of-shakuntala.jpg",
                            Language = "Sanskrit",
                            Link = "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
                            Pages = 147,
                            Title = "The recognition of Shakuntala",
                            Year = 150
                        },
                        new
                        {
                            BookId = 52,
                            Author = "Yasunari Kawabata",
                            Country = "Japan",
                            ImageLink = "images/the-sound-of-the-mountain.jpg",
                            Language = "Japanese",
                            Link = "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
                            Pages = 288,
                            Title = "The Sound of the Mountain",
                            Year = 1954
                        },
                        new
                        {
                            BookId = 53,
                            Author = "Nikos Kazantzakis",
                            Country = "Greece",
                            ImageLink = "images/zorba-the-greek.jpg",
                            Language = "Greek",
                            Link = "https://en.wikipedia.org/wiki/Zorba_the_Greek\n",
                            Pages = 368,
                            Title = "Zorba the Greek",
                            Year = 1946
                        },
                        new
                        {
                            BookId = 54,
                            Author = "D. H. Lawrence",
                            Country = "United Kingdom",
                            ImageLink = "images/sons-and-lovers.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
                            Pages = 432,
                            Title = "Sons and Lovers",
                            Year = 1913
                        },
                        new
                        {
                            BookId = 55,
                            Author = "Halldór Laxness",
                            Country = "Iceland",
                            ImageLink = "images/independent-people.jpg",
                            Language = "Icelandic",
                            Link = "https://en.wikipedia.org/wiki/Independent_People\n",
                            Pages = 470,
                            Title = "Independent People",
                            Year = 1934
                        },
                        new
                        {
                            BookId = 56,
                            Author = "Giacomo Leopardi",
                            Country = "Italy",
                            ImageLink = "images/poems-giacomo-leopardi.jpg",
                            Language = "Italian",
                            Link = "\n",
                            Pages = 184,
                            Title = "Poems",
                            Year = 1818
                        },
                        new
                        {
                            BookId = 57,
                            Author = "Doris Lessing",
                            Country = "United Kingdom",
                            ImageLink = "images/the-golden-notebook.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/The_Golden_Notebook\n",
                            Pages = 688,
                            Title = "The Golden Notebook",
                            Year = 1962
                        },
                        new
                        {
                            BookId = 58,
                            Author = "Astrid Lindgren",
                            Country = "Sweden",
                            ImageLink = "images/pippi-longstocking.jpg",
                            Language = "Swedish",
                            Link = "https://en.wikipedia.org/wiki/Pippi_Longstocking\n",
                            Pages = 160,
                            Title = "Pippi Longstocking",
                            Year = 1945
                        },
                        new
                        {
                            BookId = 59,
                            Author = "Lu Xun",
                            Country = "China",
                            ImageLink = "images/diary-of-a-madman.jpg",
                            Language = "Chinese",
                            Link = "https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n",
                            Pages = 389,
                            Title = "Diary of a Madman",
                            Year = 1918
                        },
                        new
                        {
                            BookId = 60,
                            Author = "Naguib Mahfouz",
                            Country = "Egypt",
                            ImageLink = "images/children-of-gebelawi.jpg",
                            Language = "Arabic",
                            Link = "https://en.wikipedia.org/wiki/Children_of_Gebelawi\n",
                            Pages = 355,
                            Title = "Children of Gebelawi",
                            Year = 1959
                        },
                        new
                        {
                            BookId = 61,
                            Author = "Thomas Mann",
                            Country = "Germany",
                            ImageLink = "images/buddenbrooks.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/Buddenbrooks\n",
                            Pages = 736,
                            Title = "Buddenbrooks",
                            Year = 1901
                        },
                        new
                        {
                            BookId = 62,
                            Author = "Thomas Mann",
                            Country = "Germany",
                            ImageLink = "images/the-magic-mountain.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/The_Magic_Mountain\n",
                            Pages = 720,
                            Title = "The Magic Mountain",
                            Year = 1924
                        },
                        new
                        {
                            BookId = 63,
                            Author = "Herman Melville",
                            Country = "United States",
                            ImageLink = "images/moby-dick.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Moby-Dick\n",
                            Pages = 378,
                            Title = "Moby Dick",
                            Year = 1851
                        },
                        new
                        {
                            BookId = 64,
                            Author = "Michel de Montaigne",
                            Country = "France",
                            ImageLink = "images/essais.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
                            Pages = 404,
                            Title = "Essays",
                            Year = 1595
                        },
                        new
                        {
                            BookId = 65,
                            Author = "Elsa Morante",
                            Country = "Italy",
                            ImageLink = "images/history.jpg",
                            Language = "Italian",
                            Link = "https://en.wikipedia.org/wiki/History_(novel)\n",
                            Pages = 600,
                            Title = "History",
                            Year = 1974
                        },
                        new
                        {
                            BookId = 66,
                            Author = "Toni Morrison",
                            Country = "United States",
                            ImageLink = "images/beloved.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Beloved_(novel)\n",
                            Pages = 321,
                            Title = "Beloved",
                            Year = 1987
                        },
                        new
                        {
                            BookId = 67,
                            Author = "Murasaki Shikibu",
                            Country = "Japan",
                            ImageLink = "images/the-tale-of-genji.jpg",
                            Language = "Japanese",
                            Link = "https://en.wikipedia.org/wiki/The_Tale_of_Genji\n",
                            Pages = 1360,
                            Title = "The Tale of Genji",
                            Year = 1006
                        },
                        new
                        {
                            BookId = 68,
                            Author = "Robert Musil",
                            Country = "Austria",
                            ImageLink = "images/the-man-without-qualities.jpg",
                            Language = "German",
                            Link = "https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n",
                            Pages = 365,
                            Title = "The Man Without Qualities",
                            Year = 1931
                        },
                        new
                        {
                            BookId = 69,
                            Author = "Vladimir Nabokov",
                            Country = "Russia/United States",
                            ImageLink = "images/lolita.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Lolita\n",
                            Pages = 317,
                            Title = "Lolita",
                            Year = 1955
                        },
                        new
                        {
                            BookId = 70,
                            Author = "George Orwell",
                            Country = "United Kingdom",
                            ImageLink = "images/nineteen-eighty-four.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
                            Pages = 272,
                            Title = "Nineteen Eighty-Four",
                            Year = 1949
                        },
                        new
                        {
                            BookId = 71,
                            Author = "Ovid",
                            Country = "Roman Empire",
                            ImageLink = "images/the-metamorphoses-of-ovid.jpg",
                            Language = "Classical Latin",
                            Link = "https://en.wikipedia.org/wiki/Metamorphoses\n",
                            Pages = 576,
                            Title = "Metamorphoses",
                            Year = 100
                        },
                        new
                        {
                            BookId = 72,
                            Author = "Fernando Pessoa",
                            Country = "Portugal",
                            ImageLink = "images/the-book-of-disquiet.jpg",
                            Language = "Portuguese",
                            Link = "https://en.wikipedia.org/wiki/The_Book_of_Disquiet\n",
                            Pages = 272,
                            Title = "The Book of Disquiet",
                            Year = 1928
                        },
                        new
                        {
                            BookId = 73,
                            Author = "Edgar Allan Poe",
                            Country = "United States",
                            ImageLink = "images/tales-and-poems-of-edgar-allan-poe.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n",
                            Pages = 842,
                            Title = "Tales",
                            Year = 1950
                        },
                        new
                        {
                            BookId = 74,
                            Author = "Marcel Proust",
                            Country = "France",
                            ImageLink = "images/a-la-recherche-du-temps-perdu.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
                            Pages = 2408,
                            Title = "In Search of Lost Time",
                            Year = 1920
                        },
                        new
                        {
                            BookId = 75,
                            Author = "François Rabelais",
                            Country = "France",
                            ImageLink = "images/gargantua-and-pantagruel.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n",
                            Pages = 623,
                            Title = "Gargantua and Pantagruel",
                            Year = 1533
                        },
                        new
                        {
                            BookId = 76,
                            Author = "Juan Rulfo",
                            Country = "Mexico",
                            ImageLink = "images/pedro-paramo.jpg",
                            Language = "Spanish",
                            Link = "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo\n",
                            Pages = 124,
                            Title = "Pedro Páramo",
                            Year = 1955
                        },
                        new
                        {
                            BookId = 77,
                            Author = "Rumi",
                            Country = "Sultanate of Rum",
                            ImageLink = "images/the-masnavi.jpg",
                            Language = "Persian",
                            Link = "https://en.wikipedia.org/wiki/Masnavi\n",
                            Pages = 438,
                            Title = "The Masnavi",
                            Year = 1236
                        },
                        new
                        {
                            BookId = 78,
                            Author = "Salman Rushdie",
                            Country = "United Kingdom, India",
                            ImageLink = "images/midnights-children.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Midnight%27s_Children\n",
                            Pages = 536,
                            Title = "Midnight's Children",
                            Year = 1981
                        },
                        new
                        {
                            BookId = 79,
                            Author = "Saadi",
                            Country = "Persia, Persian Empire",
                            ImageLink = "images/bostan.jpg",
                            Language = "Persian",
                            Link = "https://en.wikipedia.org/wiki/Bustan_(book)\n",
                            Pages = 298,
                            Title = "Bostan",
                            Year = 1257
                        },
                        new
                        {
                            BookId = 80,
                            Author = "Tayeb Salih",
                            Country = "Sudan",
                            ImageLink = "images/season-of-migration-to-the-north.jpg",
                            Language = "Arabic",
                            Link = "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North\n",
                            Pages = 139,
                            Title = "Season of Migration to the North",
                            Year = 1966
                        },
                        new
                        {
                            BookId = 81,
                            Author = "José Saramago",
                            Country = "Portugal",
                            ImageLink = "images/blindness.jpg",
                            Language = "Portuguese",
                            Link = "https://en.wikipedia.org/wiki/Blindness_(novel)\n",
                            Pages = 352,
                            Title = "Blindness",
                            Year = 1995
                        },
                        new
                        {
                            BookId = 82,
                            Author = "William Shakespeare",
                            Country = "England",
                            ImageLink = "images/hamlet.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Hamlet\n",
                            Pages = 432,
                            Title = "Hamlet",
                            Year = 1603
                        },
                        new
                        {
                            BookId = 83,
                            Author = "William Shakespeare",
                            Country = "England",
                            ImageLink = "images/king-lear.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/King_Lear\n",
                            Pages = 384,
                            Title = "King Lear",
                            Year = 1608
                        },
                        new
                        {
                            BookId = 84,
                            Author = "William Shakespeare",
                            Country = "England",
                            ImageLink = "images/othello.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Othello\n",
                            Pages = 314,
                            Title = "Othello",
                            Year = 1609
                        },
                        new
                        {
                            BookId = 85,
                            Author = "Sophocles",
                            Country = "Greece",
                            ImageLink = "images/oedipus-the-king.jpg",
                            Language = "Greek",
                            Link = "https://en.wikipedia.org/wiki/Oedipus_the_King\n",
                            Pages = 88,
                            Title = "Oedipus the King",
                            Year = -430
                        },
                        new
                        {
                            BookId = 86,
                            Author = "Stendhal",
                            Country = "France",
                            ImageLink = "images/le-rouge-et-le-noir.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/The_Red_and_the_Black\n",
                            Pages = 576,
                            Title = "The Red and the Black",
                            Year = 1830
                        },
                        new
                        {
                            BookId = 87,
                            Author = "Laurence Sterne",
                            Country = "England",
                            ImageLink = "images/the-life-and-opinions-of-tristram-shandy.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n",
                            Pages = 640,
                            Title = "The Life And Opinions of Tristram Shandy",
                            Year = 1760
                        },
                        new
                        {
                            BookId = 88,
                            Author = "Italo Svevo",
                            Country = "Italy",
                            ImageLink = "images/confessions-of-zeno.jpg",
                            Language = "Italian",
                            Link = "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
                            Pages = 412,
                            Title = "Confessions of Zeno",
                            Year = 1923
                        },
                        new
                        {
                            BookId = 89,
                            Author = "Jonathan Swift",
                            Country = "Ireland",
                            ImageLink = "images/gullivers-travels.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n",
                            Pages = 178,
                            Title = "Gulliver's Travels",
                            Year = 1726
                        },
                        new
                        {
                            BookId = 90,
                            Author = "Leo Tolstoy",
                            Country = "Russia",
                            ImageLink = "images/war-and-peace.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/War_and_Peace\n",
                            Pages = 1296,
                            Title = "War and Peace",
                            Year = 1867
                        },
                        new
                        {
                            BookId = 91,
                            Author = "Leo Tolstoy",
                            Country = "Russia",
                            ImageLink = "images/anna-karenina.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/Anna_Karenina\n",
                            Pages = 864,
                            Title = "Anna Karenina",
                            Year = 1877
                        },
                        new
                        {
                            BookId = 92,
                            Author = "Leo Tolstoy",
                            Country = "Russia",
                            ImageLink = "images/the-death-of-ivan-ilyich.jpg",
                            Language = "Russian",
                            Link = "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich\n",
                            Pages = 92,
                            Title = "The Death of Ivan Ilyich",
                            Year = 1886
                        },
                        new
                        {
                            BookId = 93,
                            Author = "Mark Twain",
                            Country = "United States",
                            ImageLink = "images/the-adventures-of-huckleberry-finn.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n",
                            Pages = 224,
                            Title = "The Adventures of Huckleberry Finn",
                            Year = 1884
                        },
                        new
                        {
                            BookId = 94,
                            Author = "Valmiki",
                            Country = "India",
                            ImageLink = "images/ramayana.jpg",
                            Language = "Sanskrit",
                            Link = "https://en.wikipedia.org/wiki/Ramayana\n",
                            Pages = 152,
                            Title = "Ramayana",
                            Year = -450
                        },
                        new
                        {
                            BookId = 95,
                            Author = "Virgil",
                            Country = "Roman Empire",
                            ImageLink = "images/the-aeneid.jpg",
                            Language = "Classical Latin",
                            Link = "https://en.wikipedia.org/wiki/Aeneid\n",
                            Pages = 442,
                            Title = "The Aeneid",
                            Year = -23
                        },
                        new
                        {
                            BookId = 96,
                            Author = "Vyasa",
                            Country = "India",
                            ImageLink = "images/the-mahab-harata.jpg",
                            Language = "Sanskrit",
                            Link = "https://en.wikipedia.org/wiki/Mahabharata\n",
                            Pages = 276,
                            Title = "Mahabharata",
                            Year = -700
                        },
                        new
                        {
                            BookId = 97,
                            Author = "Walt Whitman",
                            Country = "United States",
                            ImageLink = "images/leaves-of-grass.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Leaves_of_Grass\n",
                            Pages = 152,
                            Title = "Leaves of Grass",
                            Year = 1855
                        },
                        new
                        {
                            BookId = 98,
                            Author = "Virginia Woolf",
                            Country = "United Kingdom",
                            ImageLink = "images/mrs-dalloway.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/Mrs_Dalloway\n",
                            Pages = 216,
                            Title = "Mrs Dalloway",
                            Year = 1925
                        },
                        new
                        {
                            BookId = 99,
                            Author = "Virginia Woolf",
                            Country = "United Kingdom",
                            ImageLink = "images/to-the-lighthouse.jpg",
                            Language = "English",
                            Link = "https://en.wikipedia.org/wiki/To_the_Lighthouse\n",
                            Pages = 209,
                            Title = "To the Lighthouse",
                            Year = 1927
                        },
                        new
                        {
                            BookId = 100,
                            Author = "Marguerite Yourcenar",
                            Country = "France/Belgium",
                            ImageLink = "images/memoirs-of-hadrian.jpg",
                            Language = "French",
                            Link = "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n",
                            Pages = 408,
                            Title = "Memoirs of Hadrian",
                            Year = 1951
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
